### ISSUE TITLE
Edge from label is always null string ""

### ISSUE THREAD

**Issue by rjurney** [bfontaine/Graphs.rb#5]
{
    "edges": [
        {
            "": "AmazonWebServices",
            "weight": 1.0,
            "directed": true
        },
        {
            "": "Cloudera",
            "weight": 1.0,
            "directed": true
        },
        {
            "": "Mapr",
            "weight": 1.0,
            "directed": true
        },
        {
            "": "Hortonworks",
            "weight": 1.0,
            "directed": true
        },
        {
            "": "At&T",
            "weight": 2.0,
            "directed": true
        },
        {
            "": "HewlattPackard",
            "weight": 1.0,
            "directed": true
        },
        {
            "": "Google",
            "weight": 1.0,
            "directed": true
        },
        {
            "": "Polycom",
            "weight": 1.0,
            "directed": true
        },
        {
            "": "Ibm",
            "weight": 1.0,
            "directed": true
        },
        ...
    ]
}

**Comment by bfontaine** [comment]
Hello,
Could you please provide a minimal code example to reproduce the issue?

**Comment by rjurney** [comment]
https://gist.github.com/rjurney/726433d4a36daa7cc17d

That file loaded with GDF::load() reproduces the issue.

**Comment by bfontaine** [comment]
Thanks, I can confirm the bug, I’ll work on it.

**Comment by rjurney** [comment]
Thanks, also I can't build the gem :(

Russells-MacBook-Pro:Graphs.rb rjurney$ gem cert --add <(curl -Ls https://gist.github.com/bfontaine/5233818/raw/gem-public-key.pem)
Added '/CN=batifon/DC=yahoo/DC=fr'

Russells-MacBook-Pro:Graphs.rb rjurney$  gem build graphs.gemspec
ERROR:  While executing gem ... (Gem::Security::Exception)
    certificate /CN=batifon/DC=yahoo/DC=fr does not match the signing key

**Comment by bfontaine** [comment]
I fixed the issue and released the [v0.2.0](https://rubygems.org/gems/graphs/versions/0.2.0). Regarding the building issue I guess you’d have to sign with your own key but I’m not sure.

**Comment by rjurney** [comment]
Now I get this issue when parsing a GDF file:

jruby-1.7.4 :005 >   g = GDF::load('../data/BigHadoopPartner.gdf')
CSV::MalformedCSVError: Missing or stray quote in line 1
    from /Users/rjurney/.rvm/rubies/jruby-1.7.4/lib/ruby/1.9/csv.rb:1895:in `shift'
    from org/jruby/RubyArray.java:1617:in`each'
    from /Users/rjurney/.rvm/rubies/jruby-1.7.4/lib/ruby/1.9/csv.rb:1887:in `shift'
    from org/jruby/RubyKernel.java:1489:in`loop'
    from /Users/rjurney/.rvm/rubies/jruby-1.7.4/lib/ruby/1.9/csv.rb:1849:in `shift'
    from /Users/rjurney/.rvm/rubies/jruby-1.7.4/lib/ruby/1.9/csv.rb:1396:in`parse_line'
    from /Users/rjurney/.rvm/rubies/jruby-1.7.4/lib/ruby/1.9/csv.rb:2354:in `parse_csv'
    from /Users/rjurney/.rvm/gems/jruby-1.7.4/gems/graphs-0.2.0/lib/graphs/gdf.rb:101:in`parse'
    from org/jruby/RubyString.java:7127:in `each_line'
    from /Users/rjurney/.rvm/gems/jruby-1.7.4/gems/graphs-0.2.0/lib/graphs/gdf.rb:85:in`parse'
    from /Users/rjurney/.rvm/gems/jruby-1.7.4/gems/graphs-0.2.0/lib/graphs/gdf.rb:63:in `load'
    from (irb):5:in`evaluate'
    from org/jruby/RubyKernel.java:1093:in `eval'
    from org/jruby/RubyKernel.java:1489:in`loop'
    from org/jruby/RubyKernel.java:1254:in `catch'
    from org/jruby/RubyKernel.java:1254:in`catch'
    from /Users/rjurney/.rvm/rubies/jruby-1.7.4/bin/irb:13:in `(root)'jruby-1.7.4 :006 > 

Line 1-2 looks like:

nodedef> name VARCHAR,label VARCHAR,width DOUBLE,height DOUBLE,x DOUBLE,y DOUBLE,color VARCHAR,group INTEGER,PageRank DOUBLE default 0.0,Modularity Class INTEGER default 0
Auren,"Auren",1.0028039,1.0028039,1169.1615,473.4499,'30,110,229',2,1.4706891233271104E-4,13

**Comment by rjurney** [comment]
Actually, this line is messing it up: 

LINE: Securboration,,","Securboration,",1.0017138,1.0017138,868.6553,-414.62808,'30,229,205',1,1.4695786844141188E-4,4

**Comment by bfontaine** [comment]
You have an unclosed quote here:

```
Securboration,,","Securboration,",1.0017138,1.0017138,868.6553,-414.62808,'30,229,205',1,1.4695786844141188E-4,4
               ^
```

The parser thinks you open a quote for a field but it’s never closed, hence the error.

Edit: in fact, this part is strange: `","Securboration,"`. What are these quotes for?

**Comment by rjurney** [comment]
Thanks, yeah. I have many corrupted lines. I must clean Gephi's output before loading it.
